export interface ChainConfig {
  id: string;
  name: string;
  chainId?: number;
  rpcUrl: string;
  rpcFallbacks?: string[];
  nativeToken: string;
  nativeTokenSymbol: string;
  explorerUrl: string;
  color: string;
  icon: string;
  isEIP1559?: boolean;
  chainType?: "evm" | "solana";
  computeUnitsPerSwap?: number;
  signaturesPerSwap?: number;
}

export const chains: ChainConfig[] = [
  {
    id: "ethereum",
    name: "Ethereum",
    chainId: 1,
    rpcUrl: "https://ethereum-rpc.publicnode.com",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://etherscan.io",
    color: "#627EEA",
    icon: "E",
    isEIP1559: true,
  },
  {
    id: "solana",
    name: "Solana",
    chainType: "solana",
    rpcUrl: "https://api.mainnet-beta.solana.com",
    rpcFallbacks: ["https://solana-rpc.publicnode.com"],
    nativeToken: "solana",
    nativeTokenSymbol: "SOL",
    explorerUrl: "https://solscan.io",
    color: "#9945FF",
    icon: "$",
    computeUnitsPerSwap: 300000,
    signaturesPerSwap: 1,
  },
  {
    id: "polygon",
    name: "Polygon",
    chainId: 137,
    rpcUrl: "https://polygon-bor-rpc.publicnode.com",
    nativeToken: "matic-network",
    nativeTokenSymbol: "POL",
    explorerUrl: "https://polygonscan.com",
    color: "#8247E5",
    icon: "P",
    isEIP1559: true,
  },
  {
    id: "arbitrum",
    name: "Arbitrum",
    chainId: 42161,
    rpcUrl: "https://arbitrum-one-rpc.publicnode.com",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://arbiscan.io",
    color: "#28A0F0",
    icon: "A",
    isEIP1559: true,
  },
  {
    id: "optimism",
    name: "Optimism",
    chainId: 10,
    rpcUrl: "https://optimism-rpc.publicnode.com",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://optimistic.etherscan.io",
    color: "#FF0420",
    icon: "O",
    isEIP1559: true,
  },
  {
    id: "base",
    name: "Base",
    chainId: 8453,
    rpcUrl: "https://base-rpc.publicnode.com",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://basescan.org",
    color: "#0052FF",
    icon: "B",
    isEIP1559: true,
  },
  {
    id: "bsc",
    name: "BNB Chain",
    chainId: 56,
    rpcUrl: "https://bsc-rpc.publicnode.com",
    nativeToken: "binancecoin",
    nativeTokenSymbol: "BNB",
    explorerUrl: "https://bscscan.com",
    color: "#F0B90B",
    icon: "N",
    isEIP1559: false,
  },
  {
    id: "avalanche",
    name: "Avalanche",
    chainId: 43114,
    rpcUrl: "https://avalanche-c-chain-rpc.publicnode.com",
    nativeToken: "avalanche-2",
    nativeTokenSymbol: "AVAX",
    explorerUrl: "https://snowtrace.io",
    color: "#E84142",
    icon: "V",
    isEIP1559: true,
  },
  {
    id: "berachain",
    name: "Berachain",
    chainId: 80094,
    rpcUrl: "https://rpc.berachain.com",
    rpcFallbacks: ["https://berachain-rpc.publicnode.com"],
    nativeToken: "berachain-bera",
    nativeTokenSymbol: "BERA",
    explorerUrl: "https://berascan.com",
    color: "#D4A853",
    icon: "R",
    isEIP1559: true,
  },
  {
    id: "gnosis",
    name: "Gnosis",
    chainId: 100,
    rpcUrl: "https://gnosis-rpc.publicnode.com",
    nativeToken: "xdai",
    nativeTokenSymbol: "xDAI",
    explorerUrl: "https://gnosisscan.io",
    color: "#04795B",
    icon: "G",
    isEIP1559: true,
  },
  {
    id: "scroll",
    name: "Scroll",
    chainId: 534352,
    rpcUrl: "https://scroll-rpc.publicnode.com",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://scrollscan.com",
    color: "#FFEEDA",
    icon: "S",
    isEIP1559: true,
  },
  {
    id: "zksync",
    name: "zkSync Era",
    chainId: 324,
    rpcUrl: "https://mainnet.era.zksync.io",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://explorer.zksync.io",
    color: "#8C8DFC",
    icon: "Z",
    isEIP1559: true,
  },
  {
    id: "linea",
    name: "Linea",
    chainId: 59144,
    rpcUrl: "https://linea-rpc.publicnode.com",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://lineascan.build",
    color: "#61DFFF",
    icon: "L",
    isEIP1559: true,
  },
  {
    id: "mantle",
    name: "Mantle",
    chainId: 5000,
    rpcUrl: "https://mantle-rpc.publicnode.com",
    nativeToken: "mantle",
    nativeTokenSymbol: "MNT",
    explorerUrl: "https://mantlescan.xyz",
    color: "#2FF2A3",
    icon: "M",
    isEIP1559: true,
  },
  {
    id: "celo",
    name: "Celo",
    chainId: 42220,
    rpcUrl: "https://celo-rpc.publicnode.com",
    nativeToken: "celo",
    nativeTokenSymbol: "CELO",
    explorerUrl: "https://celoscan.io",
    color: "#FCFF52",
    icon: "C",
    isEIP1559: true,
  },
  {
    id: "blast",
    name: "Blast",
    chainId: 81457,
    rpcUrl: "https://blast-rpc.publicnode.com",
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://blastscan.io",
    color: "#FCFC03",
    icon: "X",
    isEIP1559: true,
  },
  {
    id: "katana",
    name: "Katana",
    chainId: 747474,
    rpcUrl: "https://rpc.katana.network",
    rpcFallbacks: ["https://katana.drpc.org"],
    nativeToken: "ethereum",
    nativeTokenSymbol: "ETH",
    explorerUrl: "https://katanascan.com",
    color: "#9655FF",
    icon: "K",
    isEIP1559: true,
  },
];

export const SWAP_GAS_LIMIT = 184000;
export const SOLANA_BASE_FEE_LAMPORTS = 5000;

export const COMMON_TRANSACTIONS = [
  { name: "ETH Transfer", gasLimit: 21000, icon: "arrow-right" },
  { name: "ERC-20 Transfer", gasLimit: 65000, icon: "coin" },
  { name: "ERC-20 Approve", gasLimit: 46000, icon: "check" },
  { name: "Uniswap Swap", gasLimit: SWAP_GAS_LIMIT, icon: "swap" },
  { name: "NFT Transfer", gasLimit: 85000, icon: "image" },
  { name: "NFT Mint", gasLimit: 150000, icon: "plus" },
  { name: "Bridge Deposit", gasLimit: 250000, icon: "bridge" },
  { name: "Contract Deploy", gasLimit: 1500000, icon: "code" },
];

export const SOLANA_COMMON_TRANSACTIONS = [
  { name: "SOL Transfer", computeUnits: 450, signatures: 1, icon: "arrow-right" },
  { name: "SPL Token Transfer", computeUnits: 50000, signatures: 1, icon: "coin" },
  { name: "Jupiter Swap", computeUnits: 300000, signatures: 1, icon: "swap" },
  { name: "NFT Transfer", computeUnits: 100000, signatures: 1, icon: "image" },
  { name: "NFT Mint", computeUnits: 200000, signatures: 1, icon: "plus" },
];
